// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLxJmkP9GP_ynqC8M8saB0lSV6C4cwwus',
    appId: '1:780322506635:web:6391fdebe6024c1059518e',
    messagingSenderId: '780322506635',
    projectId: 'gallery-bloc-firebase-app',
    authDomain: 'gallery-bloc-firebase-app.firebaseapp.com',
    storageBucket: 'gallery-bloc-firebase-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL-apxeyvXdbvalHIkclCJR9DVKe20HwM',
    appId: '1:780322506635:android:27522552f9b5795e59518e',
    messagingSenderId: '780322506635',
    projectId: 'gallery-bloc-firebase-app',
    storageBucket: 'gallery-bloc-firebase-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs1t5xGJjH059PrUGZreUQqOy3esB51XE',
    appId: '1:780322506635:ios:727aee709c30ae9c59518e',
    messagingSenderId: '780322506635',
    projectId: 'gallery-bloc-firebase-app',
    storageBucket: 'gallery-bloc-firebase-app.appspot.com',
    iosClientId: '780322506635-d5hmlv5hfnvnf2l0se97n10tv4vhrhi6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gallaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs1t5xGJjH059PrUGZreUQqOy3esB51XE',
    appId: '1:780322506635:ios:727aee709c30ae9c59518e',
    messagingSenderId: '780322506635',
    projectId: 'gallery-bloc-firebase-app',
    storageBucket: 'gallery-bloc-firebase-app.appspot.com',
    iosClientId: '780322506635-d5hmlv5hfnvnf2l0se97n10tv4vhrhi6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gallaryApp',
  );
}
